version: '3'
# for development
services:
  nginx-web:
    build: .
    ports:
      - "80:80"
    links:
      - node-part:node-part
      - react-part:react-part
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
    container_name: docker-outer-web
  node-part:
    build: ./node-part
    ports:
      - "8080"
    container_name: docker-base-node-part
    environment:
      NODE_ENV: development
      NODE_PORT: 8080
  react-part:
    build: ./react-part
    ports:
      - "8080"
    container_name: docker-base-react-part
    environment:
      NODE_ENV: development
      NODE_PORT: 8080
