version: '3'
# for development
services:
  nginx-web-dev:
    build: .
    ports:
      - "80:80"
    links:
      - node-part-dev:node-part-dev
      - react-part-dev:react-part-dev
    volumes:
      - ./nginx-development.conf:/etc/nginx/nginx.conf
    container_name: docker-outer-web-dev
  node-part-dev:
    build: ./node-part
    links:
      - mongodb:mongodb
    ports:
      - ${NODE_PORT}
    container_name: docker-base-node-part-dev
    environment:
      NODE_ENV: ${NODE_ENV}
      NODE_PORT: ${NODE_PORT}
      MONGODB_URL: ${MONGODB_URL}
    volumes:
      - ./node-part/app:/app
  react-part-dev:
    build: ./react-part
    ports:
      - "8080"
    container_name: docker-base-react-part-dev
    volumes:
      - ./react-part/app:/app
    environment:
      NODE_ENV: ${NODE_ENV}
      NODE_PORT: ${NODE_PORT}
  mongodb:
    image: tutum/mongodb:3.2
    container_name: docker-base-mongodb-part
    volumes:
      - ./data/:/data/db/
    environment:
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_PASS: ${MONGODB_PASS}
