version: '3'
# for development
services:
  nginx-web:
    build: .
    ports:
      - "80:80"
    links:
      - node-part1:node-part1
      - node-part2:node-part2
      - react-part1:react-part1
      - react-part2:react-part2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: docker-outer-web
    restart: on-failure
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 10m
    #   timeout: 10s
    #   retries: 3
  node-part1:
    build: ./node-part
    ports:
      - "3030"
    container_name: docker-base-node-part1
  node-part2:
    build: ./node-part
    ports:
      - "3030"
    container_name: docker-base-node-part2
  react-part1:
    build: ./react-part
    ports:
      - "8080"
    environment:
      NODE_ENV: development
      NODE_PORT: 8080
  react-part2:
    build: ./react-part
    ports:
      - "8080"
    environment:
      NODE_ENV: development
      NODE_PORT: 8080

